name: Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@master
      - name: Test
        uses: n8maninger/action-golang-test@v1
        env:
          AWS_EC2_METADATA_DISABLED: true
        with:
          package: "./..."
          args: "-race;-tags='testing';-timeout=30m"
